"""empty message

Revision ID: 9838cf64dfe6
Revises: d14a03b11533
Create Date: 2020-08-13 16:58:47.679083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9838cf64dfe6'
down_revision = 'd14a03b11533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'artist_id')
    # ### end Alembic commands ###
