"""empty message

Revision ID: d3e10d151a80
Revises: e03e713c8890
Create Date: 2020-08-17 10:49:37.704133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e10d151a80'
down_revision = 'e03e713c8890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('availability', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'availability')
    # ### end Alembic commands ###
